file_format: "1"
id: keyball_neo47
name: Keyball Neo
type: board
arch: arm
outputs:
  - usb
  - ble
url: https://github.com/tangbonze/zmk-config-Skinner47
siblings:
  - keyball_neo47_left
  - keyball_neo47_right
